import type { ImageSourcePropType } from 'react-native'
import type { StickerKey } from './catalog'

export const stickerSources: Partial<Record<StickerKey, ImageSourcePropType>> = {
  aiLetter: require('../../assets/stickers/ai-letter.png'),
  bookStack: require('../../assets/stickers/book-stack.png'),
  catAgreement: require('../../assets/stickers/cat-agreement.png'),
  catCompanion: require('../../assets/stickers/cat-companion.png'),
  catTutorCelebrate: require('../../assets/stickers/cat-tutor-celebrate.png'),
  catTutorIdle: require('../../assets/stickers/cat-tutor-idle.png'),
  catTutorListening: require('../../assets/stickers/cat-tutor-listening.png'),
  catTutorReading: require('../../assets/stickers/cat-tutor-reading.png'),
  catTutorSpeaking: require('../../assets/stickers/cat-tutor-speaking.png'),
  catTutorWorried: require('../../assets/stickers/cat-tutor-worried.png'),
  citrusCorner: require('../../assets/stickers/citrus-corner.png'),
  deskMat: require('../../assets/stickers/desk-mat.png'),
  emptyAi: require('../../assets/stickers/empty-ai.png'),
  emptyFeedback: require('../../assets/stickers/empty-feedback.png'),
  emptySearch: require('../../assets/stickers/empty-search.png'),
  emptyWrongWords: require('../../assets/stickers/empty-wrong-words.png'),
  flowerSmall: require('../../assets/stickers/flower-small.png'),
  headset: require('../../assets/stickers/headset.png'),
  ieltsPaper: require('../../assets/stickers/ielts-paper.png'),
  leafSprig: require('../../assets/stickers/leaf-sprig.png'),
  lemonCorner: require('../../assets/stickers/lemon-corner.png'),
  micBubble: require('../../assets/stickers/mic-bubble.png'),
  practiceModeDictation: require('../../assets/stickers/practice-mode-dictation.png'),
  practiceModeFollow: require('../../assets/stickers/practice-mode-follow.png'),
  practiceModeListening: require('../../assets/stickers/practice-mode-listening.png'),
  practiceModeMeaning: require('../../assets/stickers/practice-mode-meaning.png'),
  practiceModeQuickMemory: require('../../assets/stickers/practice-mode-quickmemory.png'),
  practiceModeRadio: require('../../assets/stickers/practice-mode-radio.png'),
  practiceModeSmart: require('../../assets/stickers/practice-mode-smart.png'),
  practiceModeTest: require('../../assets/stickers/practice-mode-test.png'),
  recordingMic: require('../../assets/stickers/recording-mic.png'),
  reviewClock: require('../../assets/stickers/review-clock.png'),
  scrollNote: require('../../assets/stickers/scroll-note.png'),
  studyWindow: require('../../assets/stickers/study-window.png'),
  studyBadgePractice: require('../../assets/stickers/study-badge-practice.png'),
  studyBadgeTodo: require('../../assets/stickers/study-badge-todo.png'),
  studyBadgeWrong: require('../../assets/stickers/study-badge-wrong.png'),
  studyDecorBanner: require('../../assets/stickers/study-decor-banner.png'),
  studyDecorMascot: require('../../assets/stickers/study-decor-mascot.png'),
  studyHeroBoard: require('../../assets/stickers/study-hero-board.png'),
  studyLoungeRoom: require('../../assets/stickers/study-lounge-room.png'),
  tapePin: require('../../assets/stickers/tape-pin.png'),
  treasureBox: require('../../assets/stickers/treasure-box.png'),
  treasureChest: require('../../assets/stickers/treasure-chest.png'),
  vocabCardStack: require('../../assets/stickers/vocab-card-stack.png'),
  wrongWordSticky: require('../../assets/stickers/wrong-word-sticky.png'),
  wrongWordKit: require('../../assets/stickers/wrong-word-kit.png'),
}
