import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  answerButton: {
    alignItems: 'center',
    borderRadius: theme.radius.control,
    flex: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    justifyContent: 'center',
    minHeight: 48,
  },
  answerButtonText: {
    color: theme.colors.text,
    fontWeight: '900',
  },
  answerRow: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  choiceButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.control,
    flexBasis: '48%',
    flexGrow: 1,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.sm,
  },
  choiceText: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '800',
    textAlign: 'center',
  },
  choiceWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.sm,
  },
  confirmButton: {
    backgroundColor: theme.colors.emeraldSoft,
  },
  definition: {
    color: theme.colors.text,
    fontSize: theme.typography.body,
    lineHeight: 23,
    marginTop: theme.spacing.sm,
  },
  entryGrid: {
    gap: theme.spacing.sm,
  },
  entryGroup: {
    marginBottom: theme.spacing.sm,
  },
  entryGroupHeader: {
    marginBottom: theme.spacing.xs,
  },
  entryGroupSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
  },
  entryGroupTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
    marginBottom: 2,
  },
  entryCopy: {
    flex: 1,
  },
  entrySubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
    marginTop: 2,
  },
  entryTag: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 1,
    color: theme.colors.primaryDark,
    fontSize: 11,
    fontWeight: '800',
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: 2,
  },
  entryTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.xs,
    marginTop: theme.spacing.xs,
  },
  entryTile: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    minHeight: 72,
    overflow: 'visible',
    paddingHorizontal: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
  },
  entryTilePressed: {
    backgroundColor: '#FFF0D4',
    borderColor: '#E7A94B',
    transform: [{ scale: 0.98 }],
  },
  entryTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  practiceHero: {
    backgroundColor: '#FFF1D6',
    borderColor: '#E9A55F',
    overflow: 'visible',
    paddingVertical: theme.spacing.md,
  },
  practiceHeroEyebrow: {
    alignSelf: 'flex-start',
    backgroundColor: '#FFFFFF',
    borderRadius: theme.radius.pill,
    color: '#D8662B',
    fontSize: theme.typography.caption,
    fontWeight: '900',
    marginBottom: theme.spacing.xs,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  modeShortcut: {
    alignItems: 'center',
    backgroundColor: '#FFF7E8',
    borderColor: '#F2BC72',
    borderRadius: 18,
    borderWidth: 1,
    flexBasis: '30%',
    flexGrow: 1,
    gap: theme.spacing.xs,
    minHeight: 92,
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: theme.spacing.sm,
  },
  modeShortcutIcon: {
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderColor: '#F1C58B',
    borderRadius: 18,
    borderWidth: 1,
    height: 54,
    justifyContent: 'center',
    width: 58,
  },
  modeShortcutLabel: {
    color: theme.colors.text,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  modeShortcutPressed: {
    backgroundColor: '#FFE2B3',
    borderColor: '#DA7A20',
    transform: [{ scale: 0.96 }],
  },
  modeShortcutRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
    marginTop: theme.spacing.md,
  },
  practiceRoot: {
    flex: 1,
  },
  practiceStatusOverlay: {
    left: theme.spacing.lg,
    position: 'absolute',
    right: theme.spacing.lg,
    top: theme.spacing.sm,
    zIndex: 20,
  },
  exampleBox: {
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.card,
    marginTop: theme.spacing.md,
    padding: theme.spacing.md,
  },
  exampleHint: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
    marginTop: theme.spacing.xs,
  },
  exampleText: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    lineHeight: 20,
    marginTop: theme.spacing.xs,
  },
  exampleTitle: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  completedCard: {
    backgroundColor: theme.colors.surfaceElevated,
    overflow: 'visible',
    paddingRight: 124,
  },
  micStrip: {
    alignItems: 'center',
    backgroundColor: theme.colors.infoSoft,
    borderRadius: theme.radius.control,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    marginTop: theme.spacing.sm,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  micText: {
    color: theme.colors.info,
    flex: 1,
    fontSize: theme.typography.caption,
    fontWeight: '700',
  },
  mobileControlActionRow: {
    flexDirection: 'row',
    gap: theme.spacing.xs,
  },
  mobileControlCopy: {
    flex: 1,
    minWidth: 0,
  },
  mobileControlIconButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.control,
    borderWidth: 1,
    flex: 1,
    gap: 2,
    minHeight: 52,
    paddingVertical: theme.spacing.xs,
  },
  mobileControlIconButtonActive: {
    backgroundColor: theme.colors.roseSoft,
    borderColor: theme.colors.rose,
  },
  mobileControlIconButtonDisabled: {
    opacity: 0.45,
  },
  mobileControlIconText: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  mobileControlLabel: {
    color: theme.colors.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  mobileControlPrimary: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.control,
    borderWidth: 1,
    flex: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minHeight: 46,
    paddingHorizontal: theme.spacing.sm,
  },
  mobileControlSurface: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    gap: theme.spacing.xs,
    marginBottom: theme.spacing.md,
    padding: theme.spacing.sm,
  },
  mobileControlTinyText: {
    color: theme.colors.text,
    fontSize: 11,
    fontWeight: '900',
  },
  mobileControlValue: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  progressFill: {
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radius.pill,
    height: '100%',
  },
  progressMini: {
    marginBottom: theme.spacing.md,
  },
  progressTrack: {
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.pill,
    height: 7,
    overflow: 'hidden',
  },
  practiceWordListIndex: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    width: 28,
  },
  practiceWordListRow: {
    alignItems: 'center',
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  practiceWordListRowActive: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  practiceStatusBar: {
    backgroundColor: theme.colors.surfaceElevated,
    borderBottomColor: theme.colors.border,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.xs,
    minHeight: 54,
    paddingHorizontal: theme.spacing.xs,
    paddingVertical: theme.spacing.xs,
  },
  rejectButton: {
    backgroundColor: theme.colors.dangerSoft,
  },
  radioControls: {
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  sheetBackdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(15, 23, 42, 0.28)',
  },
  sheetBody: {
    flex: 1,
  },
  sheetGrabber: {
    alignSelf: 'center',
    backgroundColor: '#E8B45F',
    borderRadius: theme.radius.pill,
    height: 4,
    marginBottom: theme.spacing.md,
    width: 42,
  },
  sheetGroup: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    marginBottom: theme.spacing.xs,
    marginTop: theme.spacing.md,
  },
  sheetIcon: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.card,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  sheetIndex: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  sheetLabel: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  sheetMeta: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
    marginTop: 2,
  },
  sheetPanel: {
    backgroundColor: '#FFF8ED',
    borderColor: '#F4CF97',
    borderWidth: 1,
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    marginTop: 'auto',
    maxHeight: '78%',
    overflow: 'visible',
    padding: theme.spacing.lg,
  },
  sheetRoot: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheetRow: {
    alignItems: 'center',
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    padding: theme.spacing.md,
  },
  sheetRowActive: {
    backgroundColor: theme.colors.primarySoft,
    borderColor: theme.colors.primary,
  },
  sheetScroll: {
    marginTop: theme.spacing.sm,
  },
  sheetScrollContent: {
    paddingBottom: theme.spacing.lg,
  },
  sheetSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    lineHeight: 18,
    marginBottom: theme.spacing.md,
  },
  sheetTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
  },
  statRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.xs,
    marginTop: theme.spacing.sm,
  },
  statusLabel: {
    color: theme.colors.muted,
    fontSize: 11,
    fontWeight: '900',
  },
  statusSegment: {
    backgroundColor: theme.colors.surfaceInset,
    borderRadius: theme.radius.control,
    flex: 1,
    justifyContent: 'center',
    minWidth: 0,
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: theme.spacing.xs,
  },
  statusValue: {
    color: theme.colors.text,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    marginTop: 2,
  },
  word: {
    color: theme.colors.text,
    fontSize: 30,
    fontWeight: '900',
    marginTop: theme.spacing.md,
  },
  wordMeta: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    marginTop: theme.spacing.xs,
  },
  workbench: {
    backgroundColor: theme.colors.surfaceElevated,
  },
  workbenchTop: {
    flexDirection: 'row',
    gap: theme.spacing.xs,
  },
})
