import { StyleSheet } from 'react-native'
import { theme } from '../theme'

export const styles = StyleSheet.create({
  chapterFill: { backgroundColor: theme.colors.primary, borderRadius: theme.radius.pill, height: '100%' },
  chapterList: { gap: theme.spacing.sm },
  chapterName: { color: theme.colors.text, flex: 1, fontSize: theme.typography.caption, fontWeight: '900' },
  chapterRow: { alignItems: 'center', flexDirection: 'row', gap: theme.spacing.sm },
  chapterTrack: { backgroundColor: theme.colors.surfaceInset, borderRadius: theme.radius.pill, flex: 1, height: 8, overflow: 'hidden' },
  chapterValue: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '800', width: 36 },
  dailyBar: { backgroundColor: theme.colors.primary, borderRadius: theme.radius.pill, bottom: 0, position: 'absolute', width: '100%' },
  dailyBarWrap: { backgroundColor: theme.colors.surfaceInset, borderRadius: theme.radius.pill, flex: 1, marginVertical: theme.spacing.xs, overflow: 'hidden', width: 16 },
  dailyChart: { flexDirection: 'row', gap: theme.spacing.sm, height: 180, justifyContent: 'space-between' },
  dailyColumn: { alignItems: 'center', flex: 1 },
  dailyDate: { color: theme.colors.muted, fontSize: 10, fontWeight: '800' },
  dailyValue: { color: theme.colors.text, fontSize: 11, fontWeight: '900' },
  detailCard: { paddingVertical: theme.spacing.lg },
  detailCopy: { flex: 1 },
  detailEntry: { alignItems: 'center', borderTopColor: theme.colors.border, borderTopWidth: 1, flexDirection: 'row', gap: theme.spacing.sm, minHeight: 60, paddingVertical: theme.spacing.sm },
  detailIcon: { alignItems: 'center', backgroundColor: theme.colors.primarySoft, borderRadius: theme.radius.pill, height: 36, justifyContent: 'center', width: 36 },
  detailLabel: { color: theme.colors.text, fontSize: theme.typography.label, fontWeight: '900' },
  detailList: { marginTop: theme.spacing.md },
  detailMeta: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '700', marginTop: 2 },
  heroCard: { backgroundColor: theme.colors.accentSubtle },
  heroMeta: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '800', marginTop: theme.spacing.md },
  legendDot: { borderRadius: theme.radius.pill, height: 9, width: 9 },
  legendName: { color: theme.colors.text, flex: 1, fontSize: theme.typography.caption, fontWeight: '900' },
  legendRow: { alignItems: 'center', flexDirection: 'row', gap: theme.spacing.sm, marginTop: theme.spacing.sm },
  legendValue: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '800' },
  metricCard: { backgroundColor: theme.colors.surfaceElevated, borderColor: theme.colors.border, borderRadius: theme.radius.card, borderWidth: 1, flexBasis: '48%', flexGrow: 1, minHeight: 72, padding: theme.spacing.sm },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.sm },
  metricLabel: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '800', lineHeight: 18, marginTop: 2 },
  metricValue: { color: theme.colors.text, fontSize: 18, fontWeight: '900' },
  profileLabel: { color: theme.colors.text, fontSize: theme.typography.label, fontWeight: '900' },
  profileRow: { alignItems: 'center', borderBottomColor: theme.colors.border, borderBottomWidth: 1, flexDirection: 'row', gap: theme.spacing.md, justifyContent: 'space-between', paddingVertical: theme.spacing.sm },
  profileValue: { color: theme.colors.muted, flex: 1, fontSize: theme.typography.label, fontWeight: '700', textAlign: 'right' },
  sectionHead: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: theme.spacing.sm },
  sectionMeta: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '900' },
  stackBar: { borderRadius: theme.radius.pill, flexDirection: 'row', height: 16, overflow: 'hidden' },
  stackSlice: { height: '100%' },
  stageFill: { backgroundColor: theme.colors.success, borderRadius: theme.radius.pill, height: '100%' },
  stageList: { gap: theme.spacing.sm },
  stageName: { color: theme.colors.text, fontSize: theme.typography.caption, fontWeight: '900', width: 38 },
  stageRow: { alignItems: 'center', flexDirection: 'row', gap: theme.spacing.sm },
  stageTrack: { backgroundColor: theme.colors.surfaceInset, borderRadius: theme.radius.pill, flex: 1, height: 9, overflow: 'hidden' },
  stageValue: { color: theme.colors.muted, fontSize: theme.typography.caption, fontWeight: '800', width: 42 },
  topicBox: { backgroundColor: theme.colors.surfaceInset, borderRadius: theme.radius.card, gap: theme.spacing.xs, marginTop: theme.spacing.md, padding: theme.spacing.md },
  topicText: { color: theme.colors.muted, fontSize: theme.typography.caption, lineHeight: 19 },
  wordChip: { backgroundColor: theme.colors.accentSoft, borderRadius: theme.radius.pill, color: theme.colors.accentDark, fontSize: theme.typography.caption, fontWeight: '800', paddingHorizontal: theme.spacing.sm, paddingVertical: theme.spacing.xs },
  wordStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: theme.spacing.xs, marginTop: theme.spacing.md },
})
