import { StatusBar, StyleSheet } from 'react-native'
import { theme } from '../theme'

const statusBarInset = StatusBar.currentHeight ?? 0
const sceneTopInset = Math.max(statusBarInset - 10, 0)

export const styles = StyleSheet.create({
  bigBoard: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    elevation: 2,
    marginBottom: theme.spacing.lg,
    marginTop: theme.spacing.md,
    overflow: 'visible',
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  boardHeader: {
    marginBottom: theme.spacing.md,
  },
  boardSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    marginTop: 2,
  },
  boardTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
  },
  heroBoard: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    left: 18,
    paddingHorizontal: 42,
    paddingTop: 46,
    position: 'absolute',
    top: 60 + sceneTopInset,
    zIndex: 5,
  },
  heroBoardArt: {
    left: 0,
    position: 'absolute',
    top: 0,
  },
  heroBoardContent: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroButton: {
    alignItems: 'center',
    backgroundColor: 'transparent',
    bottom: 16,
    borderRadius: 24,
    justifyContent: 'center',
    minHeight: 34,
    minWidth: 128,
    paddingHorizontal: theme.spacing.md,
    position: 'absolute',
  },
  heroButtonText: {
    color: '#4F3B35',
    fontSize: 18,
    fontWeight: '900',
  },
  heroEyebrow: {
    backgroundColor: 'rgba(255, 221, 104, 0.42)',
    borderRadius: theme.radius.pill,
    color: '#B88312',
    fontSize: theme.typography.caption,
    fontWeight: '900',
    letterSpacing: 1,
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  heroHint: {
    color: '#806F67',
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 3,
    textAlign: 'center',
  },
  heroTitle: {
    color: '#3D1614',
    fontSize: 21,
    fontWeight: '900',
    lineHeight: 28,
    marginTop: 4,
    textAlign: 'center',
  },
  heroRewardCopy: {
    flex: 1,
  },
  heroRewardIcon: {
    marginRight: 6,
  },
  heroRewardLabel: {
    color: '#B88312',
    fontSize: 10,
    fontWeight: '900',
    includeFontPadding: false,
    lineHeight: 12,
  },
  heroRewardPlaque: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 247, 210, 0.84)',
    borderColor: 'rgba(184, 131, 18, 0.34)',
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    marginTop: 6,
    maxWidth: 160,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  heroRewardValue: {
    color: '#4F3B35',
    fontSize: 12,
    fontWeight: '900',
    includeFontPadding: false,
    lineHeight: 14,
  },
  iconBadge: {
    alignItems: 'center',
    height: 16,
    justifyContent: 'center',
    position: 'absolute',
    right: 5,
    top: 5,
    width: 31,
  },
  iconBadgeTodo: {
    right: 5,
    top: 9,
  },
  iconBadgeWrong: {
    right: 10,
    top: 9,
    width: 38,
  },
  iconBadgeText: {
    color: '#5C301D',
    fontSize: 9,
    fontWeight: '900',
    height: '100%',
    includeFontPadding: false,
    lineHeight: 13,
    textAlign: 'center',
    textAlignVertical: 'center',
    width: '100%',
  },
  iconBubble: {
    alignItems: 'center',
    height: 106,
    justifyContent: 'center',
    width: 92,
  },
  iconDock: {
    alignItems: 'center',
    position: 'absolute',
    right: 0,
    top: 138 + sceneTopInset,
    width: 96,
    zIndex: 8,
  },
  iconEntry: {
    alignItems: 'center',
    marginBottom: -2,
    minHeight: 104,
    width: 96,
  },
  iconEntryLabel: {
    color: '#70412A',
    fontSize: 11,
    fontWeight: '900',
    includeFontPadding: false,
    lineHeight: 16,
    textAlign: 'center',
    textAlignVertical: 'center',
    width: '100%',
  },
  iconEntryLabelFrame: {
    alignItems: 'center',
    bottom: 7,
    height: 24,
    justifyContent: 'center',
    left: 17,
    position: 'absolute',
    right: 17,
  },
  iconEntryLabelFrameTodo: {
    bottom: 3,
    left: 14,
    right: 14,
  },
  iconEntryLabelFrameWrong: {
    bottom: 5,
    left: 12,
    right: 12,
  },
  planTicket: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: theme.spacing.md,
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  roomStatCell: {
    alignItems: 'center',
    flex: 1,
  },
  roomStatLabel: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '800',
    marginTop: 2,
  },
  roomStats: {
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    elevation: 2,
    flexDirection: 'row',
    marginBottom: theme.spacing.md,
    padding: theme.spacing.md,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  roomStatValue: {
    color: theme.colors.text,
    fontSize: 20,
    fontWeight: '900',
  },
  scene: {
    backgroundColor: '#FFF2E4',
    elevation: 0,
    flex: 1,
    minHeight: 0,
    overflow: 'hidden',
  },
  sceneDraggableStage: {
    left: 0,
    position: 'absolute',
    top: 0,
  },
  sceneWideWallpaper: {
    left: 0,
    position: 'absolute',
    top: 0,
    zIndex: 0,
  },
  sceneHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    left: 18,
    position: 'absolute',
    right: 18,
    top: 12 + sceneTopInset,
    zIndex: 8,
  },
  sceneHeaderActions: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: theme.spacing.sm,
  },
  sceneHeaderAiIcon: {
    transform: [{ translateX: -9 }],
  },
  sceneHeaderButton: {
    alignItems: 'center',
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  sceneHeaderIcon: {
    height: 42,
    width: 42,
  },
  sceneHeaderSearchIcon: {
    transform: [{ translateX: -6 }],
  },
  roomSceneArt: {
    position: 'absolute',
    zIndex: 3,
  },
  roomSpeech: {
    left: 44,
    position: 'absolute',
    top: 344 + sceneTopInset,
    zIndex: 6,
  },
  roomSpeechBubble: {
    height: 94,
    justifyContent: 'center',
    paddingBottom: 16,
    paddingHorizontal: 28,
    paddingTop: 10,
    width: 252,
  },
  roomSpeechText: {
    color: '#7A351A',
    fontSize: 14,
    fontWeight: '900',
    lineHeight: 21,
  },
  ticketButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.pill,
    borderWidth: 2,
    elevation: 2,
    justifyContent: 'center',
    minHeight: 46,
    paddingHorizontal: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  ticketButtonText: {
    color: theme.colors.textInverse,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
  ticketEyebrow: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  ticketTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.title,
    fontWeight: '900',
    marginTop: 2,
  },
  todoCopy: {
    flex: 1,
  },
  todoCta: {
    color: theme.colors.primaryDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
  },
  todoIndex: {
    color: theme.colors.accentDark,
    fontSize: theme.typography.caption,
    fontWeight: '900',
    width: 28,
  },
  todoSubtitle: {
    color: theme.colors.muted,
    fontSize: theme.typography.caption,
    fontWeight: '700',
    lineHeight: 18,
    marginTop: 2,
  },
  todoTicket: {
    alignItems: 'center',
    backgroundColor: theme.colors.surfaceElevated,
    borderColor: theme.colors.border,
    borderRadius: theme.radius.card,
    borderWidth: 2,
    elevation: 2,
    flexDirection: 'row',
    gap: theme.spacing.md,
    marginBottom: theme.spacing.md,
    padding: theme.spacing.lg,
    shadowColor: theme.colors.shadow,
    shadowOffset: { height: 4, width: 0 },
    shadowOpacity: 1,
    shadowRadius: 0,
  },
  todoTitle: {
    color: theme.colors.text,
    fontSize: theme.typography.label,
    fontWeight: '900',
  },
})
